# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reports_backlog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportsWindow(object):
    def setupUi(self, ReportsWindow):
        ReportsWindow.setObjectName("ReportsWindow")
        ReportsWindow.resize(1100, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReportsWindow.sizePolicy().hasHeightForWidth())
        ReportsWindow.setSizePolicy(sizePolicy)
        ReportsWindow.setMinimumSize(QtCore.QSize(1100, 600))
        ReportsWindow.setMaximumSize(QtCore.QSize(1100, 600))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        ReportsWindow.setFont(font)
        self.tableWidget = QtWidgets.QTableWidget(ReportsWindow)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1081, 581))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(ReportsWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportsWindow)

    def retranslateUi(self, ReportsWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportsWindow.setWindowTitle(_translate("ReportsWindow", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportsWindow = QtWidgets.QDialog()
    ui = Ui_ReportsWindow()
    ui.setupUi(ReportsWindow)
    ReportsWindow.show()
    sys.exit(app.exec_())
